### ISSUE TITLE
Error api playlist get all

### ISSUE THREAD

**Issue by agungjati** [pojok-projects/tutorialsystem-frontend-controller#38]
![image](https://user-images.githubusercontent.com/21965071/68083084-323d5180-fe57-11e9-8f61-c9f058685d01.png)
![image](https://user-images.githubusercontent.com/21965071/68083085-3ec1aa00-fe57-11e9-94b6-46986b0f09c8.png)

**Comment by JuniYadi** [comment]
## Import Comment From SLACK
Iman Suherman 3:10 PM

saya sudah perbaiki issue dengan pm API yang return 422, silahkan lihat hasilnya disini: https://api.tutorialinaja.tech/pm/v1/playlists

update reflected langsung ke front end dan bisa dilihat di: https://beta.tutorialinaja.tech/

Untuk lihat script apa saja yang di update bisa lihat detailnya di: https://github.com/pojok-projects/tutorialsystem-playlist-manager/commit/897725049aafd6ab8ab11ff34d80d1fda3a7e2ae
